# M2. Capítulo 9

Laura Cecilia Diaz Seguy, A01620523 <br />
Syeni Perea Zelaya, A010125129 <br />
Delfos Gonzalez Zazueta, A01740425 <br />
Denisse Alexandra Cavazos Céspedes, A01383022 <br />
Kevin Montoya Campaña, A01740352

In Problems 1, 2, 3, 4, 5, 6, Z. 8, 9, and 10 use the improved Euler's method to obtain a four-decimal approximation of the indicated value. First use $h = 0.1$ and then use $h= 0.05$.

In [332]:
import numpy as np
import pandas as pd
import sympy as sp
from IPython.display import display, Math, Latex

x = sp.symbols('x')
g = sp.Function('g')

## Función que resuelve ecuaciones diferenciales a través del método de Euler mejorado

In [194]:
def edo_solver_improved_euler_method(edo, a: int, b: int, y: int, n: int):
    
    interval, delta = np.linspace(a, b, n + 1, endpoint = True, retstep = True)
    
    for x_n_1, x_n in zip(interval, interval[1:]):
        y = y + delta * (edo(x_n_1, y) + edo(x_n, y + delta * edo(x_n_1, y)))/2
    return y

## Función que regresa tabla comparando la solución a través del método de Euler mejorado con una solución analítica

In [451]:
def comparison_table_improved_euler_method_and_analytic_method(edo, a: int, b: int, y: int, n: int, x_def: int, diffeq):
    
    interval, delta = np.linspace(a, b, n + 1, endpoint = True, retstep = True)
    
    sol = sp.dsolve(diffeq, g(x), ics = {g(x_def): y})
    
    tb = pd.DataFrame({'xn': [a], 'yn': [y], 'y': [y], '|y - yn|': [0], '|(y - yn)/y| * 100%': [0]})
    tb.index.name = 'n'
    
    for i, [x_n_1, x_n] in enumerate(zip(interval, interval[1:])):
        
        y = y + delta * (edo(x_n_1, y) + edo(x_n, y + delta * edo(x_n_1, y)))/2
        
        y_ex = (sol.evalf(subs = {x: x_n}).rhs)
        
        abs_error = abs(y_ex - y)
        
        rel_error = abs((y_ex - y)/y_ex) * 100
        
        new_row = {'xn': x_n, 'yn': y, 'y': y_ex, '|y - yn|': abs_error, '|(y - yn)/y| * 100%': rel_error}
        tb = tb.append(new_row, ignore_index = True)
    
    return tb

### Función que convierte h a número de divisiones

In [198]:
def h_to_n(a, b, h):
    n = (b - a)/h
    return int(n)

## 1. $y' = 2x -3y +1, y(1) = 5; y\left(\frac{3}{2}\right)$

In [382]:
edo_1 = lambda x, y: 2*x - 3*y + 1
diffeq_1 = sp.Eq(sp.Derivative(g(x), x), (2 * x) - (3 * g(x)) + 1)

### Solución con $h = 0.1$

In [452]:
n = h_to_n(a = 1, b = 1.5, h = 0.1)
comparison_table_improved_euler_method_and_analytic_method(edo_1, 1, 1.5, 5, n, 1, diffeq_1)

    xn        yn                 y            |y - yn| |(y - yn)/y| * 100%
0  1.0  5.000000                 5                   0                   0
1  1.1  3.990000  3.97234359843392  0.0176564015660814   0.444483240901979
2  1.2  3.254550  3.22831579684145  0.0262342031585545   0.812628156892886
3  1.3  2.723640  2.69440523001586  0.0292345199841377    1.08500828525951
4  1.4  2.345112  2.31615333918485  0.0289582745651464    1.25027449932732
5  1.5  2.080108  2.05321623173781  0.0268919205059355    1.30974614803111

### Solución con $h = 0.05$

In [453]:
n = h_to_n(a = 1, b = 1.5, h = 0.05)
comparison_table_improved_euler_method_and_analytic_method(edo_1, 1, 1.5, 5, n, 1, diffeq_1)

      xn        yn                 y             |y - yn| |(y - yn)/y| * 100%
0   1.00  5.000000                 5                    0                   0
1   1.05  4.447500  4.44521145601691  0.00228854398308975  0.0514833547455216
2   1.10  3.976284  3.97234359843392  0.00394077656608083  0.0992053297613646
3   1.15  3.575075  3.56998552906971  0.00508938889903909   0.142560491004716
4   1.20  3.234158  3.22831579684145  0.00584247625914003   0.180975983355044
5   1.25  2.945169  2.93888100046206  0.00628781224581765   0.213952597768642
6   1.30  2.700902  2.69440523001586  0.00649640992879874   0.241107382676825
7   1.35  2.495152  2.48862605180266  0.00652548559968436   0.262212379998095
8   1.40  2.322574  2.31615333918485  0.00642092240291081   0.277223545362095
9   1.45  2.178567  2.17234776717154  0.00621931562092026   0.286294658475332
10  1.50  2.059166  2.05321623173781  0.00594966831719379   0.289773099648549

## 3. $y' = 1 + y^2, y(0) = 0; y\left(\frac{1}{2}\right)$

In [454]:
edo_3 = lambda x, y: y ** 2 + 1
diffeq_3 = sp.Eq(sp.Derivative(g(x), x), 1 + g(x) ** 2)

### Solución con $h = 0.1$

In [455]:
n = h_to_n(a = 0, b = 0.5, h = 0.1)
comparison_table_improved_euler_method_and_analytic_method(edo_3, 0, 0.5, 0, n, 0, diffeq_3)

    xn        yn                  y              |y - yn| |(y - yn)/y| * 100%
0  0.0  0.000000                  0                     0                   0
1  0.1  0.100500  0.100334672085451  0.000165327914549443   0.164776453755329
2  0.2  0.203035  0.202710035508673  0.000325291500102520   0.160471334971772
3  0.3  0.309814  0.309336249609623  0.000477536047976790   0.154374422195728
4  0.4  0.423408  0.422793218738162  0.000615127522588299   0.145491340760896
5  0.5  0.547024  0.546302489843790  0.000721810707980941   0.132126563835968

### Solución con $h = 0.05$

In [456]:
n = h_to_n(a = 0, b = 0.5, h = 0.05)
comparison_table_improved_euler_method_and_analytic_method(edo_3, 0, 0.5, 0, n, 0, diffeq_3)

,xn,yn,y,|y - yn|,|(y - yn)/y| * 100%
0,0.00,0.000000,0,0,0
1,0.05,0.050063,0.0500417083755388,2.07916244612111e-5,0.0415485904381601
2,0.10,0.100376,0.100334672085451,4.14242075224835e-5,0.0412860346891894
3,0.15,0.151197,0.151135218058295,6.18805888466523e-5,0.0409438578523663
4,0.20,0.202792,0.202710035508673,8.21153770767247e-5,0.0405087872786700
5,0.25,0.255444,0.255341921221036,0.000102038543209282,0.0399615318633686
6,0.30,0.309458,0.309336249609623,0.000121493774249470,0.0392756343308595
7,0.35,0.365169,0.365028494830425,0.000140228695198308,0.0384158215548218
8,0.40,0.422951,0.422793218738162,0.000157852788648605,0.0373356954777375
9,0.45,0.483229,0.483055065616578,0.000173776798658654,0.0359745318966570
10,0.50,0.546490,0.546302489843790,0.000187124140061501,0.0342528440818579

## 5. $y' = e^{-y}, y(0) = 0; y\left(\frac{1}{2}\right)$

In [457]:
edo_5 = lambda x, y: np.exp(-y)
diffeq_5 = sp.Eq(sp.Derivative(g(x), x), sp.exp(-g(x)))

### Solución con $h = 0.1$

In [458]:
n = h_to_n(a = 0, b = 0.5, h = 0.1)
comparison_table_improved_euler_method_and_analytic_method(edo_5, 0, 0.5, 0, n, 0, diffeq_5)

    xn        yn                   y              |y - yn| |(y - yn)/y| * 100%
0  0.0  0.000000                   0                     0                   0
1  0.1  0.095242  0.0953101798043249   6.83089025269590e-5  0.0716701014174976
2  0.2  0.182207   0.182321556793955  0.000114879904505816  0.0630095017429255
3  0.3  0.262217   0.262364264467491  0.000146912892279027  0.0559957708330477
4  0.4  0.336303   0.336472236621213  0.000168978068516012  0.0502205085961494
5  0.5  0.405281   0.405465108108164  0.000184068342845567  0.0453968391273914

### Solución con $h = 0.05$

In [459]:
n = h_to_n(a = 0, b = 0.5, h = 0.05)
comparison_table_improved_euler_method_and_analytic_method(edo_5, 0, 0.5, 0, n, 0, diffeq_5)

,xn,yn,y,|y - yn|,|(y - yn)/y| * 100%
0,0.00,0.000000,0,0,0
1,0.05,0.048781,0.0487901641694320,9.42855691419414e-6,0.0193247083191848
2,0.10,0.095293,0.0953101798043249,1.71835853414737e-5,0.0180291185860232
3,0.15,0.139738,0.139761942375159,2.35849343845074e-5,0.0168750762787763
4,0.20,0.182293,0.182321556793955,2.88829796030454e-5,0.0158417798262258
5,0.25,0.223110,0.223143551314210,3.32756089742592e-5,0.0149121983486781
6,0.30,0.262327,0.262364264467491,3.69206061870964e-5,0.0140722694312171
7,0.35,0.300065,0.300104592450338,3.99447941801800e-5,0.0133102908736027
8,0.40,0.336430,0.336472236621213,4.24508659483402e-5,0.0126164542948992
9,0.45,0.371519,0.371563556432483,4.45225428822305e-5,0.0119824837800853
10,0.50,0.405419,0.405465108108164,4.62285091164527e-5,0.0114013532094408

## 7. $y' = (x-y)^2, y(0) = \frac{1}{2}; y\left(\frac{1}{2}\right)$

In [481]:
edo_7 = lambda x, y: (x - y) ** 2
diffeq_7 = sp.Eq(sp.Derivative(g(x), x), (x - g(x)) ** 2)

### Solución con $h = 0.1$

In [489]:
n = h_to_n(a = 0, b = 0.5, h = 0.1)
comparison_table_improved_euler_method_and_analytic_method(edo_7, 0, 0.5, 0.5, n, 0, diffeq_7)

    xn        yn     y   |y - yn| |(y - yn)/y| * 100%
0  0.0  0.500000   0.5          0                   0
1  0.1  0.521531  O(1)  Abs(O(1))       100*Abs(O(1))
2  0.2  0.536172  O(1)  Abs(O(1))       100*Abs(O(1))
3  0.3  0.544885  O(1)  Abs(O(1))       100*Abs(O(1))
4  0.4  0.549021  O(1)  Abs(O(1))       100*Abs(O(1))
5  0.5  0.550263  O(1)  Abs(O(1))       100*Abs(O(1))

El software no está dando la solución analítica correcta, o esta no existe. Se buscó la solución en WolframAlpha, esta resultó ser: $y(x) = \frac{e^{2x}(x-1)+3(x+1)}{e^{2x}+3}$. Se utilizará esta función para crear la tabla y obtener los valores requeridos.

In [490]:
a = 0
b = 0.5
y = 0.5

interval, delta = np.linspace(a, b, n + 1, endpoint = True, retstep = True)

sol = lambda x, y: ((np.exp(2*x)*(x-1))+3*(x+1))/ (np.exp(2*x) + 3)

tb = pd.DataFrame({'xn': [a], 'yn': [y], 'y': [y], '|y - yn|': [0], '|(y - yn)/y| * 100%': [0]})
tb.index.name = 'n'

for i, [x_n_1, x_n] in enumerate(zip(interval, interval[1:])):

    y = y + delta * (edo(x_n_1, y) + edo(x_n, y + delta * edo(x_n_1, y)))/2

    y_ex = sol(x_n, y)

    abs_error = abs(y_ex - y)

    rel_error = abs((y_ex - y)/y_ex) * 100

    new_row = {'xn': x_n, 'yn': y, 'y': y_ex, '|y - yn|': abs_error, '|(y - yn)/y| * 100%': rel_error}
    tb = tb.append(new_row, ignore_index = True)
    
tb

    xn        yn         y  |y - yn|  |(y - yn)/y| * 100%
0  0.0  0.500000  0.500000  0.000000             0.000000
1  0.1  0.467500  0.521328  0.053828            10.325254
2  0.2  0.460287  0.535760  0.075473            14.087007
3  0.3  0.471914  0.544266  0.072352            13.293516
4  0.4  0.497576  0.548206  0.050630             9.235647
5  0.5  0.533694  0.549266  0.015572             2.835065

### Solución con $h = 0.05$

In [492]:
n = h_to_n(a = 0, b = 0.5, h = 0.05)
comparison_table_improved_euler_method_and_analytic_method(edo_7, 0, 0.5, 0.5, n, 0, diffeq_7)

      xn        yn     y   |y - yn| |(y - yn)/y| * 100%
0   0.00  0.500000   0.5          0                   0
1   0.05  0.511598  O(1)  Abs(O(1))       100*Abs(O(1))
2   0.10  0.521382  O(1)  Abs(O(1))       100*Abs(O(1))
3   0.15  0.529436  O(1)  Abs(O(1))       100*Abs(O(1))
4   0.20  0.535868  O(1)  Abs(O(1))       100*Abs(O(1))
5   0.25  0.540813  O(1)  Abs(O(1))       100*Abs(O(1))
6   0.30  0.544428  O(1)  Abs(O(1))       100*Abs(O(1))
7   0.35  0.546896  O(1)  Abs(O(1))       100*Abs(O(1))
8   0.40  0.548419  O(1)  Abs(O(1))       100*Abs(O(1))
9   0.45  0.549218  O(1)  Abs(O(1))       100*Abs(O(1))
10  0.50  0.549525  O(1)  Abs(O(1))       100*Abs(O(1))

El software no está dando la solución analítica correcta. Se buscó la solución en WolframAlpha, esta resultó ser: $y(x) = \frac{e^{2x}(x-1)+3(x+1)}{e^{2x}+3}$. Se utilizará esta función para crear la tabla y obtener los valores requeridos.

In [493]:
a = 0
b = 0.5
y = 0.5

interval, delta = np.linspace(a, b, n + 1, endpoint = True, retstep = True)

sol = lambda x, y: ((np.exp(2*x)*(x-1))+3*(x+1))/ (np.exp(2*x) + 3)

tb = pd.DataFrame({'xn': [a], 'yn': [y], 'y': [y], '|y - yn|': [0], '|(y - yn)/y| * 100%': [0]})
tb.index.name = 'n'

for i, [x_n_1, x_n] in enumerate(zip(interval, interval[1:])):

    y = y + delta * (edo(x_n_1, y) + edo(x_n, y + delta * edo(x_n_1, y)))/2

    y_ex = sol(x_n, y)

    abs_error = abs(y_ex - y)

    rel_error = abs((y_ex - y)/y_ex) * 100

    new_row = {'xn': x_n, 'yn': y, 'y': y_ex, '|y - yn|': abs_error, '|(y - yn)/y| * 100%': rel_error}
    tb = tb.append(new_row, ignore_index = True)
    
tb

      xn        yn         y  |y - yn|  |(y - yn)/y| * 100%
0   0.00  0.500000  0.500000  0.000000             0.000000
1   0.05  0.479375  0.511571  0.032196             6.293610
2   0.10  0.466237  0.521328  0.055092            10.567573
3   0.15  0.459546  0.529355  0.069809            13.187507
4   0.20  0.458409  0.535760  0.077351            14.437571
5   0.25  0.462055  0.540678  0.078622            14.541476
6   0.30  0.469820  0.544266  0.074446            13.678309
7   0.35  0.481132  0.546708  0.065576            11.994699
8   0.40  0.495500  0.548206  0.052706             9.614302
9   0.45  0.512500  0.548981  0.036481             6.645291
10  0.50  0.531765  0.549266  0.017501             3.186241

## 9. $y' = xy^2 - \frac{y}{x}, y(1) = 1; y\left(\frac{3}{2}\right)$

In [465]:
edo_9 = lambda x, y: x * y ** 2 - (y)/x
diffeq_9 = sp.Eq(sp.Derivative(g(x), x), x * g(x)**2 - g(x)/x)

### Solución con $h = 0.1$

In [496]:
n = h_to_n(a = 1, b = 1.5, h = 0.1)
comparison_table_improved_euler_method_and_analytic_method(edo_9, 1, 1.5, 1, n, 1, diffeq_9)

    xn        yn                 y              |y - yn| |(y - yn)/y| * 100%
0  1.0  1.000000                 1                     0                   0
1  1.1  1.009545  1.01010101010101  0.000555555555555642  0.0550000000000086
2  1.2  1.040439  1.04166666666667   0.00122724154311626   0.117815188139161
3  1.3  1.096688  1.09890109890110   0.00221322982726790   0.201403914281379
4  1.4  1.186553  1.19047619047619   0.00392302950222145   0.329534478186602
5  1.5  1.325970  1.33333333333333   0.00736350234312444   0.552262675734333

### Solución con $h = 0.05$

In [494]:
n = h_to_n(a = 1, b = 1.5, h = 0.05)
comparison_table_improved_euler_method_and_analytic_method(edo_9, 1, 1.5, 1, n, 1, diffeq_9)

,xn,yn,y,|y - yn|,|(y - yn)/y| * 100%
0,1.00,1.000000,1,0,0
1,1.05,1.002440,1.00250626566416,6.57894736841858e-5,0.00656249999999753
2,1.10,1.009966,1.01010101010101,0.000134812601875867,0.0133464475857108
3,1.15,1.022807,1.02301790281330,0.000211102483008707,0.0206352677141011
4,1.20,1.041367,1.04166666666667,0.000299830714386440,0.0287837485810982
5,1.25,1.066259,1.06666666666667,0.000408087051839701,0.0382581611099719
6,1.30,1.098355,1.09890109890110,0.000546116185945911,0.0496965729210779
7,1.35,1.138872,1.13960113960114,0.000729381718098887,0.0640032457631773
8,1.40,1.189494,1.19047619047619,0.000982165040392058,0.0825018633929329
9,1.45,1.252574,1.25391849529781,0.00134411995083816,0.107193566079343
10,1.50,1.331451,1.33333333333333,0.00188278859530078,0.141209144647558